export const CHANGE_CURRENCY = 'CHANGE_CURRENCY'
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY'
export const CHANGE_SHOW_CURRENCY = 'CHANGE_CHOW_CURRENCY'
export const CHANGE_SHOW_CART = 'CHANGE_SHOW_CART'
